// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-jv_bXdPPC8Zven1X6S3j1qNkBPslgc',
    appId: '1:1033111971494:web:82c2ad294cea25205a3667',
    messagingSenderId: '1033111971494',
    projectId: 'hikespot-taxi-app',
    authDomain: 'hikespot-taxi-app.firebaseapp.com',
    storageBucket: 'hikespot-taxi-app.appspot.com',
    measurementId: 'G-6QSPKE4DL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJeJZJeHAVOKlm_wlPl2tFdH7Xv9KWYg',
    appId: '1:1033111971494:android:758b652fd508bc2c5a3667',
    messagingSenderId: '1033111971494',
    projectId: 'hikespot-taxi-app',
    storageBucket: 'hikespot-taxi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz85GlnDa3-DkdirVUu9VwgdzWLl2doEw',
    appId: '1:1033111971494:ios:5e505eefa66ff31b5a3667',
    messagingSenderId: '1033111971494',
    projectId: 'hikespot-taxi-app',
    storageBucket: 'hikespot-taxi-app.appspot.com',
    iosBundleId: 'net.hikespot.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz85GlnDa3-DkdirVUu9VwgdzWLl2doEw',
    appId: '1:1033111971494:ios:5e505eefa66ff31b5a3667',
    messagingSenderId: '1033111971494',
    projectId: 'hikespot-taxi-app',
    storageBucket: 'hikespot-taxi-app.appspot.com',
    iosBundleId: 'net.hikespot.taxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-jv_bXdPPC8Zven1X6S3j1qNkBPslgc',
    appId: '1:1033111971494:web:fc055daca5f5e3695a3667',
    messagingSenderId: '1033111971494',
    projectId: 'hikespot-taxi-app',
    authDomain: 'hikespot-taxi-app.firebaseapp.com',
    storageBucket: 'hikespot-taxi-app.appspot.com',
    measurementId: 'G-QL376RVCZQ',
  );
}
